fix bugs

diff --git a/jungle b/jungle
--- a/jungle
+++ b/jungle
@@ -15,6 +15,10 @@ if [ $# -gt 0 ]; then
   fi
 fi
 
+if ! git -C "$JUNGLE_HOME" pull; then
+  echo -e "Unable to auto-update"
+fi
+
 if [ "$1" = 'version' ]; then
   echo -e "jungle SNAPSHOT-0.0.1"
   exit 0
@@ -80,10 +84,6 @@ JUNGLE_HOME=$JUNGLE_HOME" "$JUNGLE_HOME"/jungle >/usr/local/bin/jungle && chmod 
         Install Failure! (maybe need root?)\033[0m"
     fi
     exit 0
-  fi
-
-  if ! git -C "$JUNGLE_HOME" pull; then
-    exit 3
   fi
 
   cd "$JUNGLE_HOME" || exit 4
